### ISSUE TITLE
ImageNet pretrained R-50 not found

### ISSUE THREAD

**Issue by genos** [ethanweber/xview2#6]
Hi! I'm trying to replicate your amazing work on the xView2 challenge so I can tinker with some other ideas, but I'm having trouble getting started. I've followed along with the README's instructions but running

```
python detectron2_repo/tools/train_net.py --config-file configs/xview/joint-11.yaml
```

seems to start fine, but then it fails with

```
Traceback (most recent call last):
  File "detectron2_repo/tools/train_net.py", line 134, in <module>
    launch(
  File "/home/genos/xview2/detectron2_repo/detectron2/engine/launch.py", line 52, in launch
    main_func(*args)
  File "detectron2_repo/tools/train_net.py", line 123, in main
    trainer.resume_or_load(resume=args.resume)
  File "/home/genos/xview2/detectron2_repo/detectron2/engine/defaults.py", line 282, in resume_or_load
    self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume).get(
  File "/home/genos/xview2/venv/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 215, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/home/genos/xview2/venv/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 141, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint detectron2://ImageNetPretrained/MSRA/R-50.pkl not found!
```

Is there some other setup step I need to do to, say, download this pre-trained model from `detectron2`'s model zoo?

Thanks,
Graham

**Comment by genos** [comment]
Looks like I was able to answer my own question; changing line 11 of `configs/xview/joint-11.yml` to

```
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-50.pkl"
```

Downloaded the pre-trained weights the first time, then had no trouble using it on subsequent runs. Cheers!

**Comment by ethanweber** [comment]
Hi @genos! Sorry for no response, but thanks for answering your own question. :) I'm glad we know the solution now!
